### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by xelfer** [nZEDb/nZEDb#1749]
I have an automated script which builds an nZEDb server for me, it worked yesterday, it does not work today, so something committed recently broke the installer:

[Tue Jul 07 00:44:03.800679 2015] [:error] [pid 4174] [client 115.70.74.246:59048] PHP Warning:  require_once(/var/www/nZEDb/www/install): failed to open stream: No such file or directory in /var/www/nZEDb/www/install/index.php on line 3
[Tue Jul 07 00:44:03.802332 2015] [:error] [pid 4174] [client 115.70.74.246:59048] PHP Fatal error:  require_once(): Failed opening required '' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/nZEDb/www/install/index.php on line 3

Any ideas?

Fresh Ubuntu 14.04 box. 
Cheers,
Nick

**Comment by Fossil01** [comment]
Do those paths even exist? Check for capitals etc.

**Comment by xelfer** [comment]
index.php exists but line 3 is trying to require_once realpath('config.php');

there's a config.php.tpl in the install folder, no config.php. changing it to require config.php.tpl throws this:

[Tue Jul 07 08:03:27.361760 2015] [:error] [pid 4172] [client 115.70.74.246:56098] PHP Parse error:  syntax error, unexpected '%' in /var/www/nZEDb/www/install/config.php.tpl on line 20

**Comment by niel** [comment]
Which branch?

**Comment by niel** [comment]
add this at line 22:
require_once dirname(__DIR__) . DIRECTORY_SEPARATOR . 'libs' . DIRECTORY_SEPARATOR .  'smarty' . DIRECTORY_SEPARATOR . 'Autoloader.php';

I'm fixing it in dev, but it might take a while as I'm in the middle of another change which has broken it ;-)

**Comment by niel** [comment]
I've just pushed a potential fix, Please try it.

**Comment by niel** [comment]
Ok, trying again as I was looking at the wrong issue before ;-)
Which branch?

**Comment by xelfer** [comment]
Just cloning the master. 

Part of my script is: 
cd /var/www/ ; git clone https://github.com/nZEDb/nZEDb.git

then I usually browse to /install/ and configure, but /install/ is just a white page with the above error in apache's error.log

**Comment by kevinlekiller** [comment]
Does the latest commits fix your issue?

**Comment by xelfer** [comment]
just did a fresh checkout and same error:

> [Tue Jul 07 23:53:32.213929 2015] [:error] [pid 4180] [client 115.70.74.246:51271] PHP Warning:  require_once(/var/www/nZEDb/www/install): failed to open stream: No such file or directory in /var/www/nZEDb/www/install/index.php on line 3
> [Tue Jul 07 23:53:32.214103 2015] [:error] [pid 4180] [client 115.70.74.246:51271] PHP Fatal error:  require_once(): Failed opening required '/var/www/nZEDb/www/install' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/nZEDb/www/install/index.php on line 3

**Comment by xelfer** [comment]
You're one directory off. automated.config.php is in /var/www/nZEDb/www/

this made the installer work:
> require_once realpath('../automated.config.php');

**Comment by niel** [comment]
Updated all branches to fix the path and add same require to the stepX files.
Let me know if this does or does not fix it for you.

**Comment by xelfer** [comment]
Not working - added some debug stuff to check out what path index.php is trying to access for automated.config.php and it's trying to hit:

> /var/www/nZEDb/www/install/www

instead of 

> /var/www/nZEDb/www/

No worries regarding the inconvenience, just trying to help out!

**Comment by niel** [comment]
ok. Hopefully this latest attempt fixes it finally :-) Please let me know either way.

**Comment by xelfer** [comment]
> [Wed Jul 08 22:11:22.813979 2015] [:error] [pid 7559] [client 115.70.74.246:50805] PHP Fatal error:  Class 'InstallPage' not found in /var/www/nZEDb/www/install/step1.php on line 11

;-)

**Comment by thejrose1984** [comment]
Have nZEDb running on lighttpd and able to see the initial install page, but when I click on the pre-flight checklist and it goes to step1, I get a blank screen.

**Comment by niel** [comment]
Should be all fixed now. Test and close the issue if you're happy ;-)

**Comment by thejrose1984** [comment]
Still not working, but here's the problem...
I get to step1 now, it tells me everything looks good except for a warning about URL rewriting because I'm using lighttpd (as opposed to apache or ngnix). It allows me to proceed to step 2 (setting up the database), but when I put in my information and click (Setup Database), all it does is give me a blank page as well as change the URL from http://nzedb-app/install/step2.php to http://nzedb-app/install/step2.php?

**Comment by niel** [comment]
@thejrose1984 , sounds like you're having different problems. Already had two confirmations this fixes all installation include issues.
Check your error logs to find out *why* the page is blank. If you do not know how, see the wiki guide for setting up on Ubuntu for the instructions on enabling php error logging.

**Comment by thejrose1984** [comment]
Maybe it's a mod rewrite issue? If that's the cause I don't know what needs to be done seeing as how I tried using the rules in your URL rewriting guide and dropped it in the lighttpd.conf file and restarted the service...

**Comment by niel** [comment]
I told you what to do. Check the error logs.

**Comment by thejrose1984** [comment]
[09-Jul-2015 17:06:28 America/New_York] PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /usr/local/www/nZEDb/nzedb/db/DB.php on line 310

**Comment by kevinlekiller** [comment]
Did you install/enable pdo_mysql ?

**Comment by thejrose1984** [comment]
Trying that now

**Comment by thejrose1984** [comment]
Ran `pkg install -y php55-pdo_mysql-5.5.26` and tried again...same error

**Comment by thejrose1984** [comment]
Refreshed...
Here is the error output

[09-Jul-2015 17:25:26 America/New_York] PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/20121212/php_pdo_mysql.dll' - Cannot open &quot;/usr/local/lib/php/20121212/php_pdo_mysql.dll&quot; in Unknown on line 0
[09-Jul-2015 17:25:28 America/New_York] PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/20121212/php_pdo_mysql.dll' - Cannot open &quot;/usr/local/lib/php/20121212/php_pdo_mysql.dll&quot; in Unknown on line 0
[09-Jul-2015 17:25:30 America/New_York] PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/20121212/php_pdo_mysql.dll' - Cannot open &quot;/usr/local/lib/php/20121212/php_pdo_mysql.dll&quot; in Unknown on line 0
[09-Jul-2015 17:25:47 America/New_York] PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/20121212/php_pdo_mysql.dll' - Cannot open &quot;/usr/local/lib/php/20121212/php_pdo_mysql.dll&quot; in Unknown on line 0
[09-Jul-2015 17:25:47 America/New_York] PHP Fatal error:  Uncaught exception 'Exception' with message '/usr/bin/git: not found

/usr/bin/git branch' in /usr/local/www/nZEDb/libs/Git.php/Git.php:330
Stack trace:
#0 /usr/local/www/nZEDb/libs/Git.php/Git.php(346): GitRepo->run_command('/usr/bin/git br...')
#1 /usr/local/www/nZEDb/libs/Git.php/Git.php(503): GitRepo->run('branch')
#2 /usr/local/www/nZEDb/libs/Git.php/Git.php(543): GitRepo->list_branches(true)
#3 /usr/local/www/nZEDb/nzedb/utility/Git.php(44): GitRepo->active_branch()
#4 /usr/local/www/nZEDb/nzedb/db/DbUpdate.php(68): nzedb\utility\Git->__construct()
#5 /usr/local/www/nZEDb/www/install/step2.php(152): nzedb\db\DbUpdate->__construct(Array)
#6 {main}
  thrown in /usr/local/www/nZEDb/libs/Git.php/Git.php on line 330

**Comment by kevinlekiller** [comment]
You need to enable extensions in php.ini and restart the web server.

**Comment by thejrose1984** [comment]
Which extensions specifically?

**Comment by kevinlekiller** [comment]
https://github.com/nZEDb/nZEDb/blob/master/INSTALL.txt

**Comment by thejrose1984** [comment]
I did...same errors and then some since I uncommented the extensions mentioned...

**Comment by kevinlekiller** [comment]
Alright, dunno then, out of my field of experience.

**Comment by thejrose1984** [comment]
Nothing to do with extensions...took a closer look and it was complaining about git...why it would be complaining about git during DB setup, I will never know, but this is how it was fixed...
`ln /usr/local/bin/git /usr/bin/git`

**Comment by xelfer** [comment]
> Should be all fixed now. Test and close the issue if you're happy ;-)

Setup looking great for me now, finalised to completion. Thank you!
