### ISSUE TITLE
Problems adding to Queue

### ISSUE THREAD

**Issue by thejrose1984** [nZEDb/nZEDb#2045]
I am unable to add items to my Queue even though I have the information for my instance of SABnzbd entered correctly. There are no PHP errors, but there are a lot of errors from the web server, nginx, regarding *.js files. Please advise.

**Comment by DariusIII** [comment]
Which template are you using?

**Comment by thejrose1984** [comment]
Omicron

**Comment by DariusIII** [comment]
Can you paste the names of files reported missing? And are you on master or dev?

**Comment by thejrose1984** [comment]
Master branch

http://pastebin.com/rBiiZ6d9

**Comment by DariusIII** [comment]
Master has 2 omicron templates, which is wrong. Use the one with capital O, the other one does not belong there at all.

**Comment by thejrose1984** [comment]
I only see one omicron template

**Comment by niel** [comment]
This has already been fixed in Dev and will make it into master Monday.

**Comment by niel** [comment]
Merged to master today.

**Comment by thejrose1984** [comment]
Ran `git pull` and restarted nginx - no change and still getting errors

**Comment by Wally73** [comment]
ran nzedb/cli/update_db.php true and you did /lib/smarty/templates_c/rm -rf *  ?

**Comment by thejrose1984** [comment]
Did that, reran `git pull`, and restarted nginx again - no change and still getting errors. Also, I cannot view the queue unless using an internal address. Using a valid address that can be reached externally doesn't work.

**Comment by niel** [comment]
Yeah but the errors are different, so not the same issue.
I'll look into them later today.

**Comment by DariusIII** [comment]
Ofcourse it doesnt work: /usr/local/www/nZEDb/www/templates/Omicron/dist/css/animate.css is not a valid folder.
Templates are located in www/themes folder. How did you manage to have www/templates folder at all?

**Comment by niel** [comment]
@DariusIII,  He he trying to work that out myself.
I've fixed the other issues and pushed them out to master.

**Comment by niel** [comment]
Found it, and pushed the fix.

**Comment by niel** [comment]
Any more problems, create a new issue please.
