### ISSUE TITLE
fails to install

### ISSUE THREAD

**Issue by thejrose1984** [nZEDb/nZEDb#2257]
### Expected behaviour

complete setup process
### Actual behaviour

only initial page shows - response 500 on step1
### Steps to reproduce the behaviour

restarted nginx as well as PHP, checked logs for missing PHP dependencies, confirmed installed packages based on Wiki pages

log segment = http://pastebin.com/bCWQs1Yr

**Comment by niel** [comment]
What is line 83 of .../nzedb/db/Settings.php? Your segment indicates that is where the error comes from. If there is more to that segment it might be helpful to see.
Can you enable logging in your .../nzedb/config/settings.php

**Comment by thejrose1984** [comment]
Is this in addition to, or instead of logging configured in /usr/local/etc/php.ini?

**Comment by thejrose1984** [comment]
FYI - I tried this on two different platforms (Debian and FreeBSD) and neither worked. Not sure if that helps.

**Comment by niel** [comment]
In addition.
You didn't tell me what is at line 83 of .../nzedb/db/Settings.php Better give a few lines (say 4-5) either side, but mark which is 83.

**Comment by thejrose1984** [comment]
Why would the DB settings file help you determine why it won't install nZEDb? Also, please provide syntax to enable logging

**Comment by niel** [comment]
Why? Because that's where the damn error occurred, as I already said, when I asked the first time.

No syntax as such. Copy .../nzedb/config/settings.example.php to settings.php. Open the copy and enable appropriate settings. 
In particular make sure that: nZEDb_DEBUG, nZEDb_LOGGING, nZEDb_LOGINFO, nZEDb_LOGNOTICE, nZEDb_LOGWARNING, nZEDb_LOGERROR, nZEDb_LOGFATAL, and nZEDb_LOGQUERIES define's are set to true.

**Comment by thejrose1984** [comment]
Did that and the system designated PHP error log is empty. Only the nginx error log shows errors.

Here's a segment of Settings.php with line numbering...
http://pastebin.com/sWycJnng

**Comment by thejrose1984** [comment]
Also, no where in the error log nor my request did I mention the DB...so perhaps you should read what is being provided before being snappy...

**Comment by niel** [comment]
Take a look at your snippet again. It says the error is in Settings.php line 83. The same I asked for three times. IF you had supplied it the first time, I would know I was barking up the wrong tree. As it is I've wasted too much time on this and am going to bed.
The log is in .../resources/logs

**Comment by thejrose1984** [comment]
Log isn't there. The folder is empty.

**Comment by DariusIII** [comment]
This is most likely a database problem. Install is failing to count return values from settings table.

**Comment by kevinlekiller** [comment]
No, he wrote it fails on step 1.

**Comment by kevinlekiller** [comment]
It's also not a unique issue:

http://forums.nzedb.com/index.php?topic=2290.0

Maybe this can be used before pushing things to master? https://github.com/nZEDb/nZEDb_Misc/blob/master/Scripts/Linux/testinstall.sh

**Comment by DariusIII** [comment]
My bad. Wasn't looking which Settings was referred to.

**Comment by thejrose1984** [comment]
This seems to be an ongoing issue...

**Comment by niel** [comment]
@kevinlekiller would you mind commiting that script into the .../build/test directory of nZEDb (need to create the test directory). I had intended to use that when you created it, but forgot in this instance because I was in a bit of a hurry.

**Comment by niel** [comment]
I have a feeling we had this same issue before, but I can't remember the details so I may be wrong,

**Comment by kevinlekiller** [comment]
I was looking into travis, it's free and github has hooks for it.

I've made this so far, obviously still needs lots of work:

https://gist.github.com/kevinlekiller/4c500db7705ae0fc792f98fd60c6c424

**Comment by niel** [comment]
@kevinlekiller yeah Travis is good, looked at it myself but no time to to do anything about it yet. I have started creating test cases in lithium (yenc module is the first) but that's not finished yet.

**Comment by niel** [comment]
@kevinlekiller can you get into IRC? I'm having problem with that script and need some pointers on how to find them.

**Comment by niel** [comment]
Fixed in dev. A new release will be made soon.

**Comment by jaybird2203** [comment]
just quick update, did a composer install using the below command and still fails on the pre-flight check with the same error.

`composer create-project --stability dev --keep-vcs --prefer-source nzedb/nzedb nZEDb`

I installed v0.6.3.3 using composer as a temp work around and that has brought it back.

`composer create-project --no-dev --keep-vcs --prefer-source nzedb/nzedb nZEDb v0.6.3.3`

**Comment by thejrose1984** [comment]
@jaybird2203 installing v. 0.6.3.3 works for me too; trying to get the latest, whether from git or composer, fails the pre-flight checklist

**Comment by niel** [comment]
Because you're still downloading the older buggy version. The fix is only in dev branch until I create a new release version, which I expect to do today. We have been trying to get another, unrelated, problem fixed for that release.

**Comment by jaybird2203** [comment]
Yeah, it was the dev release at the time I posted was still failing on precheck

**Comment by niel** [comment]
When did you last try dev branch. It was updated this morning and according to Travis is passing the installer test.
If there is still a problem with it, I'd like to know before I start creating a new release ;-)

**Comment by jaybird2203** [comment]
Was last night, haven't tried since.

**Comment by jaybird2203** [comment]
All good now. Greatly appreciate the hard work niel.
