### ISSUE TITLE
parts table getting huge (again...)

### ISSUE THREAD

**Issue by danpop-chainguard** [nZEDb/nZEDb#2352]
###Expected behaviour
collections/parts releases being processed as they did prior

###Actual behaviour
parts table is getting huge by the day.  ive tried reset_truncate drop on a daily basis to no avail..

###Steps to reproduce the behaviour
latest build:

Looking up Git tag version(s)
Hash: 3cac155e0112952031b1688c2c64ccab0185eae6
XML version: 0.0.0-dev
Git version: 0.6.7.0
Looking up SQL patch version(s)
XML version: 461
 DB version: 461

run TPG, with multiple providers (Im using Giganews/Supernews as the alternate):

![image](https://cloud.githubusercontent.com/assets/22457772/21789395/b3476a0c-d6a2-11e6-8a34-29c0b406e35e.png)

could realize use some help here guys... been suffering through this and want to do my annual big donate :)

**Comment by kevinlekiller** [comment]
It's probably related to this (from IRC):

```
<allthestairs> my database has no stored procedures
<allthestairs> i guess its supposed to?
<b3rs3rk> allthestairs - yes, one of the stored procedures is critical for deletion.
<allthestairs> i wonder where it went
<allthestairs> and if there is a script to put it back
<kaibosh> the sql for the SP's is at the end here https://github.com/nZEDb/nZEDb/blob/0.x/resources/db/schema/mysql-ddl.sql
<kaibosh> personally never used SPs before but you could try re-creating it
<allthestairs> welp, re-added the triggers and SPs
<allthestairs> crossing my fingers
<kaibosh> you can use >show procedure status;  to see if they look ok .. it's odd that they vanished though
<allthestairs> yeah, when i ran that before there was nothing
<allthestairs> now they're there
```

**Comment by danpop-chainguard** [comment]
so would i just just the whole mysql-ddl.sql ?

**Comment by danpop-chainguard** [comment]
p.s. i am seeing these procedures when i do a show:


![image](https://cloud.githubusercontent.com/assets/22457772/21789776/81dd1d42-d6a5-11e6-9f45-39c6bc8f900c.png)

**Comment by kevinlekiller** [comment]
Alright, I'm not sure, just relaying what I read on IRC.

**Comment by danpop-chainguard** [comment]
thx @kevinlekiller . its been bumming me out as i had my setup running great :(

**Comment by DariusIII** [comment]
15M parts is not huge. BUT, based on releases waiting to be postprocessed (39k books) you enabled some very bad groups (by bad i mean spam releases in those groups). a.b.e-book, a.b.ebooks and similar are full of spam.

**Comment by dilbaggins** [comment]
@DariusIII (the above is me...). I have not had these issues in the past.  Is there a way to remove those items from post processing after I've disabled those groups to test?

**Comment by danpop-chainguard** [comment]
validated i am not even pulling a.b.e-book, etc...

**Comment by egyptianbman** [comment]
One thing I've noticed is that NFO processing takes a while. I have plenty of power (6 cores, 12 threads), running on an ssd and am on a gigabit connection. I've noticed that even though I have everything configured to run on 16 threads, it's 16 threads per run. This means that 16 threads start, then one by one, they finish.  Once all 16 threads finish, the loop restarts and another 16 begin.

The problem with this approach is that If you get one bad egg in the 16 that takes forever to finish, it will hold up any more processing until that one is finished.

Can anyone point me in the right direction in the code that would need to be refactored to run x number of threads at any given time? Has anyone looked into this before and run into issues leading to the current setup?

**Comment by egyptianbman** [comment]
FWIW, I found that setting `Update Binaries` in tmux settings to `disabled` for a while allows the backlog of parts to get worked through.

**Comment by DariusIII** [comment]
Issues like this come from bad releases (which should have been fixed) and MySQL not being optimized for given hardware. Having 6 cores and 12 threads does not mean too much if MySQL is not tuned well.

**Comment by danpop-chainguard** [comment]
@egyptianbman i tried this overnight and still have a large amount of parts... (i.e. as in the part count is not getting lighter...)

it seems that releases are being created sporadically....  and debuging doesnt provide where the bottleneck is.

**Comment by DariusIII** [comment]
MySQL. MySQL.

**Comment by kaibosh** [comment]
I'd say this is more an operational sizing/tuning issue rather than a coding one.

+1 for what Darius says above, 15M parts is not a lot. Have seen 10x that here when catching up after down-time. 15M would be quite normal if you're indexing spammy groups like boneless.

Focusing on the parts count question from OP, it is all about how much your DB can handle. Some options/pointers:
 - Give the DB more RAM (use mysqltuner.pl for help to know where)
 - Switch from dinnodb to cinnodb tables if RAM is maxed out and you have CPU power to spare
 - Reduce the number of groups indexed
 - Check "Delay Time Check" in site-edit. 2 is recommended, lowering this will help but dont go below 1.

In general the amount of data being pumped into Usenet is not static, its increasing. E.g. since about mid-Dec there has been a massive increase in the number of posts in particular groups. You could blacklist newzNZB posts if not already done so. And/or set "Min files to form a release" >=2 for the groups in which they post. Won't help the parts count, rather the number of releases held.

Edit: Removing stuff

**Comment by danpop-chainguard** [comment]
thank you @kaibosh  will take these suggestions under consideration.

this is what i see after mysqltuner.  not much in terms of suggestions:

![image](https://cloud.githubusercontent.com/assets/22457772/21809382/72e6c4f8-d715-11e6-934e-cd5da6ce158a.png)

**Comment by kaibosh** [comment]
Yikes, max possible mem usage 1700% of installed RAM!  I'm gonna have nightmares tonight :)

Some ideas:
 - reduce max number of connections to say 100 (that's what is potentially using all that ram)
 - reduce myisam key buffer to 250K (leaves almost 2G more for inno tables)
 - install a newer version of mysqltuner
 - optimise the db weekly/bi-weekly (ideally after a backup)

You could reduce the inno buffer pool a little, but keep as if for now to give room for more parts & releases.

**Comment by danpop-chainguard** [comment]
@kaibosh thanks dude.  looking a bit better after the above tweaks.  keeping it up for a while to see if its stable before close.  thanks all!

**Comment by danpop-chainguard** [comment]
looking good!
