### ISSUE TITLE
IRC Scraper in TMUX causing exceptions

### ISSUE THREAD

**Issue by EDChurly** [nZEDb/nZEDb#2476]
Have a strange issue after updating.

misc/IRCScraper on console works fine, IRCScraper in TMUX does not.

###Expected behaviour
IRC Scraper scrapes in TMUX

###Actual behaviour

IRCScraper in TMUX is causing the following error:

 PHP Fatal error:  Uncaught exception 'BadMethodCallException' with message 'Unhandled method call `isModified`.' in /var/www/nZEDb/libraries/lithium/data/Model.php:549
Stack trace:
#0 [internal function]: lithium\data\Model->__call('isModified', Array)
#1 [internal function]: lithium\data\Model->isModified(Object(lithium\data\entity\Record))
#2 /var/www/nZEDb/libraries/lithium/data/Entity.php(199): call_user_func_array(Array, Array)
#3 /var/www/nZEDb/nzedb/IRCScraper.php(422): lithium\data\Entity->__call('isModified', Array)
#4 /var/www/nZEDb/nzedb/IRCScraper.php(422): lithium\data\entity\Record->isModified()
#5 /var/www/nZEDb/nzedb/IRCScraper.php(300): nzedb\IRCScraper->updatePreEntry()
#6 /var/www/nZEDb/nzedb/IRCScraper.php(274): nzedb\IRCScraper->_checkForDupe()
#7 /var/www/nZEDb/nzedb/IRCClient.php(432): nzedb\IRCScraper->processChannelMessages()
#8 /var/www/nZEDb/nzedb/IRCScraper.php(193): nzedb\IRCClient->readIncoming()
#9 /var/www/nZEDb/nzedb/IRCScraper.php(136): nzedb\IRCScraper->_startScraping()
#10 /var/www/nZEDb/mis in /var/www/nZEDb/libraries/lithium/data/Model.php on line 549

I'm sure the issue is between the chair and keyboard, but not seeing where I've gone wrong.

###Steps to reproduce the behaviour
Run TMUX.

Any suggestions greatly appreciated.

**Comment by dilbaggins** [comment]
also seeing this. fresh install. fine on CLI... shit on TMUX.

```[19-Jun-2017 08:24:10 America/New_York] PHP Fatal error:  Uncaught Error: Call to a member function log() on null in /var/www/nZEDb/nzedb/IRCScraper.php:295
Stack trace:
#0 /var/www/nZEDb/nzedb/IRCScraper.php(274): nzedb\IRCScraper->_checkForDupe()
#1 /var/www/nZEDb/nzedb/IRCClient.php(432): nzedb\IRCScraper->processChannelMessages()
#2 /var/www/nZEDb/nzedb/IRCScraper.php(193): nzedb\IRCClient->readIncoming()
#3 /var/www/nZEDb/nzedb/IRCScraper.php(136): nzedb\IRCScraper->_startScraping()
#4 /var/www/nZEDb/misc/IRCScraper/scrape.php(50): nzedb\IRCScraper->__construct(false, false)
#5 {main}
  thrown in /var/www/nZEDb/nzedb/IRCScraper.php on line 295```

**Comment by EDChurly** [comment]
Yes, but strangely, only happens in tmux.. on CLI its fine.

Running 0.x - current version.

**Comment by niel** [comment]
By "on CLI" can I assume you mean running as: `php misc/IRCScraper/scrape.php true`?

**Comment by EDChurly** [comment]
correct - running in the shell/cli works fine - only in tmux is the error occurring

**Comment by niel** [comment]
I think I've found the problem, but I cannot see how it only affects Tmux. It should affect both tmux and scrape.php direct.
Looking deeper for an answer to that and a solution to the problem.

**Comment by niel** [comment]
I've pushed an attempt at fixing this to the dev branch.

**Comment by EDChurly** [comment]
Not sure if ready to test, but if so,  your last 2 commits doesn't seem to have fixed it.

The exception still occurring.

**Comment by dilbaggins** [comment]
not resolved.  (still not seeing the preDB entries in the ircscraper tab)

**Comment by niel** [comment]
Still working on this. Wally gave me a new stack trace to work with, so hopefully I can fix this soon.
